# Generated by Django 2.2.16 on 2020-10-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=500, null=True)),
                ('descripcion', models.CharField(max_length=500, null=True)),
                ('nomenclatura', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
