# Generated by Django 2.2.16 on 2020-10-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0006_auto_20181110_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkings',
            name='cameraId',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='parkings',
            name='patent',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
