# Generated by Django 2.2.16 on 2020-11-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0007_auto_20201011_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registrys',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(default=0, null=True)),
                ('idParking', models.IntegerField(default=0, null=True)),
                ('patente', models.CharField(max_length=50, null=True)),
                ('tipo', models.BooleanField(default=False)),
            ],
        ),
    ]
