# Generated by Django 2.2.16 on 2020-11-29 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0008_registrys'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=500)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
