# Generated by Django 2.2.16 on 2020-12-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0011_auto_20201204_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrys',
            name='cameraId',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
