export default {
	DEFAULT: '/',
	LOGIN: '/login',
	HOME: '/home',
	AUDIT: '/Audit',
	PARKINGS: '/parkings',
	CAMERA: '/camera',
	CONFIGUREPARKINGS: '/configureParkings',
	CONFIGUREPARKING: '/configureParking',
	CONFIGUREPATENTS: '/configurePatents',
	CAMERAADD: '/cameraAdd',
	CAMERAVIEW: '/cameraView',
	CAMERAVIEWSTATESPARK: '/cameraViewStatesPark',
	CAMERAEDIT: '/cameraEdit',
	CAMERAHOMOGRAPHY: '/cameraHomography',
	CAMERASORT: '/cameraSort',
	CAMERAPATENT: '/cameraPatent',
	CAMERAPATENTVIEW: '/cameraPatentView',
	CAMERAPATENTEDIT: '/cameraPatentEdit',
	CAMERAPATENTADD: '/cameraPatentAdd',
	CAMERAPATENTHOMOGRAPHY: '/cameraPatentHomography',
	REPORTSCUBES: '/reportsCubes',
	REPORTCUBEADD: '/reportCubeAdd',
	REPORTCUBEEDIT: '/reportCubeEdit',
	REPORTCUBEVIEW: '/reportCubeView',
	USERS: '/users',
}