# Generated by Django 2.2.16 on 2020-10-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camaras',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, null=True)),
                ('ip', models.CharField(max_length=500, null=True)),
                ('port', models.IntegerField(default=0, null=True)),
                ('x_izqsup', models.IntegerField(default=0)),
                ('y_izqsup', models.IntegerField(default=0)),
                ('x_izqinf', models.IntegerField(default=0)),
                ('y_izqinf', models.IntegerField(default=0)),
                ('x_dersup', models.IntegerField(default=0)),
                ('y_dersup', models.IntegerField(default=0)),
                ('x_derinf', models.IntegerField(default=0)),
                ('y_derinf', models.IntegerField(default=0)),
                ('filtro_contorno', models.IntegerField(default=0)),
                ('radio_parking', models.IntegerField(default=0)),
                ('radio_vehiculo', models.IntegerField(default=0)),
            ],
        ),
    ]
