# Generated by Django 2.2.16 on 2020-10-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camaras', '0002_auto_20201011_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='camaras',
            name='lastFrameImageBase64',
            field=models.TextField(default=''),
        ),
    ]
