# Generated by Django 2.2.16 on 2020-10-17 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camaras', '0003_camaras_lastframeimagebase64'),
    ]

    operations = [
        migrations.AddField(
            model_name='camaras',
            name='url',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
