# Generated by Django 2.2.16 on 2020-11-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camaras', '0005_camaras_rtmp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera_Patent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('x_izqsup', models.IntegerField(default=0)),
                ('y_izqsup', models.IntegerField(default=0)),
                ('x_izqinf', models.IntegerField(default=0)),
                ('y_izqinf', models.IntegerField(default=0)),
                ('x_dersup', models.IntegerField(default=0)),
                ('y_dersup', models.IntegerField(default=0)),
                ('x_derinf', models.IntegerField(default=0)),
                ('y_derinf', models.IntegerField(default=0)),
                ('id_camera', models.IntegerField(default=0)),
                ('distance_sensor', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('lastFrameImageBase64', models.TextField(default='')),
            ],
        ),
    ]
