# Generated by Django 2.2.16 on 2020-11-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camaras', '0006_camera_patent'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera_patent',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
