# Generated by Django 2.2.16 on 2020-11-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camaras', '0007_camera_patent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera_patent',
            name='rtmp',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='camera_patent',
            name='url',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
