# Generated by Django 2.2.16 on 2020-11-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camaras', '0008_auto_20201115_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='camaras',
            name='lastFrameDrawImg64',
            field=models.TextField(default=''),
        ),
    ]
